version: "3.4"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
       - 10000:10000

  init-azurite:
    image: mcr.microsoft.com/azure-cli
    env_file:
      - .env
    command: bash -c "
      az storage container create -n $S3_BUCKET_NAME --connection-string '$AZURE_STORAGE_CONNECTION_STRING'"
    depends_on:
      - azurite
